
version: 1.0.{build}

image: Visual Studio 2017

platform: x86

clone_depth: 1

install:
  - ps: |
      $uri = "https://netix.dl.sourceforge.net/project"
      $prj = "lazarus/Lazarus Windows 32 bits/Lazarus 1.6.4"

      $x86 = "lazarus-1.6.4-fpc-3.0.2-win32.exe"
      $x64 = "lazarus-1.6.4-fpc-3.0.2-cross-x86_64-win64-win32.exe"
      $arm = "lazarus-1.6.4-fpc-3.0.2-cross-arm-wince-win32.exe"

      $x86 = [uri]::EscapeUriString("$uri/$prj/$x86")
      $x64 = [uri]::EscapeUriString("$uri/$prj/$x64")
      $arm = [uri]::EscapeUriString("$uri/$prj/$arm")

      curl.exe -fsSL "$x86" -o "C:\lazarus-x86.exe"
      curl.exe -fsSL "$x64" -o "C:\lazarus-x64.exe"
      curl.exe -fsSL "$arm" -o "C:\lazarus-arm.exe"

  - cmd: |
      C:\lazarus-x86.exe /verysilent
      C:\lazarus-x64.exe /verysilent
      C:\lazarus-arm.exe /verysilent
      rmdir /S /Q c:\lazarus\docs
      rmdir /S /Q c:\lazarus\examples

build_script:
- ps: |
    gci -filter *.lpi -file -recurse | % {
      c:\lazarus\lazbuild $_.FullName --build-all
    }

after_build:
- 7z a cheat-engine.7z ".\Cheat Engine\bin\*"

test: off

artifacts:
- path: Cheat-Engine.7z
  name: Cheat-Engine
